/* eslint-disable react/no-unknown-property */
export default function WelcomeGate({ nodes, materials }) {
  return (
    <group
      position={[-62.367, 1.8113, 182.513]}
      rotation={[0, -0.911, -Math.PI]}
      scale={[9.082, 7.977, 9.082]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Material.039']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_1.geometry}
        material={materials['Material.028']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_2.geometry}
        material={materials['Material.029']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_3.geometry}
        material={materials['Material.030']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_4.geometry}
        material={materials['Material.031']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_5.geometry}
        material={materials['Material.032']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_6.geometry}
        material={materials['Material.033']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_7.geometry}
        material={materials['Material.034']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_8.geometry}
        material={materials['Material.035']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_9.geometry}
        material={materials['Material.020']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_10.geometry}
        material={materials['Material.021']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_11.geometry}
        material={materials['Material.022']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_12.geometry}
        material={materials['Material.023']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_13.geometry}
        material={materials['Material.024']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_14.geometry}
        material={materials['Material.025']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_15.geometry}
        material={materials['Material.026']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_16.geometry}
        material={materials['Material.027']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_17.geometry}
        material={materials['Gate Stripes.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_18.geometry}
        material={materials['Material.038']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_19.geometry}
        material={materials['Gate Blue']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_20.geometry}
        material={materials['Gate Stripes']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_21.geometry}
        material={materials['Material.040']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve003.geometry}
        material={materials['SVGMat.010']}
        position={[0.143, -1.729, -1.996]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.868, 3.364, 0.868]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve004.geometry}
        material={materials['SVGMat.011']}
        position={[0.143, -1.729, -1.996]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.199, 0.771, 0.199]}
      />
      <group
        position={[0.143, -1.105, -1.996]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.278, 12.702, 3.278]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_1.geometry}
          material={materials['SVGMat.019']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_2.geometry}
          material={materials['SVGMat.270']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_3.geometry}
          material={materials['SVGMat.269']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_4.geometry}
          material={materials['SVGMat.268']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_5.geometry}
          material={materials['SVGMat.267']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_6.geometry}
          material={materials['SVGMat.266']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_7.geometry}
          material={materials['SVGMat.265']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_8.geometry}
          material={materials['SVGMat.264']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_9.geometry}
          material={materials['SVGMat.263']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_10.geometry}
          material={materials['SVGMat.262']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_11.geometry}
          material={materials['SVGMat.261']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_12.geometry}
          material={materials['SVGMat.260']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_13.geometry}
          material={materials['SVGMat.259']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_14.geometry}
          material={materials['SVGMat.258']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_15.geometry}
          material={materials['SVGMat.257']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_16.geometry}
          material={materials['SVGMat.256']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_17.geometry}
          material={materials['SVGMat.255']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_18.geometry}
          material={materials['SVGMat.254']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_19.geometry}
          material={materials['SVGMat.253']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_20.geometry}
          material={materials['SVGMat.252']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_21.geometry}
          material={materials['SVGMat.251']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_22.geometry}
          material={materials['SVGMat.250']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_23.geometry}
          material={materials['SVGMat.249']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_24.geometry}
          material={materials['SVGMat.248']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_25.geometry}
          material={materials['SVGMat.247']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_26.geometry}
          material={materials['SVGMat.246']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_27.geometry}
          material={materials['SVGMat.245']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_28.geometry}
          material={materials['SVGMat.244']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_29.geometry}
          material={materials['SVGMat.243']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_30.geometry}
          material={materials['SVGMat.242']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_31.geometry}
          material={materials['SVGMat.241']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_32.geometry}
          material={materials['SVGMat.240']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_33.geometry}
          material={materials['SVGMat.239']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_34.geometry}
          material={materials['SVGMat.238']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_35.geometry}
          material={materials['SVGMat.237']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_36.geometry}
          material={materials['SVGMat.236']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_37.geometry}
          material={materials['SVGMat.235']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_38.geometry}
          material={materials['SVGMat.234']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_39.geometry}
          material={materials['SVGMat.232']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_40.geometry}
          material={materials['SVGMat.231']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_41.geometry}
          material={materials['SVGMat.230']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_42.geometry}
          material={materials['SVGMat.229']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_43.geometry}
          material={materials['SVGMat.228']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_44.geometry}
          material={materials['SVGMat.227']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_45.geometry}
          material={materials['SVGMat.226']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_46.geometry}
          material={materials['SVGMat.225']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_47.geometry}
          material={materials['SVGMat.224']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_48.geometry}
          material={materials['SVGMat.223']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_49.geometry}
          material={materials['SVGMat.222']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_50.geometry}
          material={materials['SVGMat.221']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_51.geometry}
          material={materials['SVGMat.220']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_52.geometry}
          material={materials['SVGMat.219']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_53.geometry}
          material={materials['SVGMat.218']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_54.geometry}
          material={materials['SVGMat.217']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_55.geometry}
          material={materials['SVGMat.216']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_56.geometry}
          material={materials['SVGMat.215']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_57.geometry}
          material={materials['SVGMat.214']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_58.geometry}
          material={materials['SVGMat.213']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_59.geometry}
          material={materials['SVGMat.212']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_60.geometry}
          material={materials['SVGMat.210']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_61.geometry}
          material={materials['SVGMat.209']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_62.geometry}
          material={materials['SVGMat.208']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_63.geometry}
          material={materials['SVGMat.207']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_64.geometry}
          material={materials['SVGMat.206']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_65.geometry}
          material={materials['SVGMat.205']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_66.geometry}
          material={materials['SVGMat.204']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_67.geometry}
          material={materials['SVGMat.203']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_68.geometry}
          material={materials['SVGMat.202']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_69.geometry}
          material={materials['SVGMat.199']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_70.geometry}
          material={materials['SVGMat.198']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_71.geometry}
          material={materials['SVGMat.197']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_72.geometry}
          material={materials['SVGMat.196']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_73.geometry}
          material={materials['SVGMat.195']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_74.geometry}
          material={materials['SVGMat.194']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_75.geometry}
          material={materials['SVGMat.193']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_76.geometry}
          material={materials['SVGMat.192']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_77.geometry}
          material={materials['SVGMat.191']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_78.geometry}
          material={materials['SVGMat.190']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_79.geometry}
          material={materials['SVGMat.189']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_80.geometry}
          material={materials['SVGMat.188']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_81.geometry}
          material={materials['SVGMat.187']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_82.geometry}
          material={materials['SVGMat.186']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_83.geometry}
          material={materials['SVGMat.185']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_84.geometry}
          material={materials['SVGMat.184']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_85.geometry}
          material={materials['SVGMat.183']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_86.geometry}
          material={materials['SVGMat.182']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_87.geometry}
          material={materials['SVGMat.181']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_88.geometry}
          material={materials['SVGMat.180']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_89.geometry}
          material={materials['SVGMat.179']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_90.geometry}
          material={materials['SVGMat.178']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_91.geometry}
          material={materials['SVGMat.177']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_92.geometry}
          material={materials['SVGMat.176']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_93.geometry}
          material={materials['SVGMat.175']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_94.geometry}
          material={materials['SVGMat.174']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_95.geometry}
          material={materials['SVGMat.173']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_96.geometry}
          material={materials['SVGMat.172']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_97.geometry}
          material={materials['SVGMat.171']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_98.geometry}
          material={materials['SVGMat.170']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_99.geometry}
          material={materials['SVGMat.169']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_100.geometry}
          material={materials['SVGMat.168']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_101.geometry}
          material={materials['SVGMat.167']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_102.geometry}
          material={materials['SVGMat.166']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_103.geometry}
          material={materials['SVGMat.165']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_104.geometry}
          material={materials['SVGMat.164']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_105.geometry}
          material={materials['SVGMat.163']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_106.geometry}
          material={materials['SVGMat.162']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_107.geometry}
          material={materials['SVGMat.161']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_108.geometry}
          material={materials['SVGMat.160']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_109.geometry}
          material={materials['SVGMat.159']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_110.geometry}
          material={materials['SVGMat.158']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_111.geometry}
          material={materials['SVGMat.157']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_112.geometry}
          material={materials['SVGMat.156']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_113.geometry}
          material={materials['SVGMat.155']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_114.geometry}
          material={materials['SVGMat.154']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_115.geometry}
          material={materials['SVGMat.153']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_116.geometry}
          material={materials['SVGMat.152']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_117.geometry}
          material={materials['SVGMat.151']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_118.geometry}
          material={materials['SVGMat.150']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_119.geometry}
          material={materials['SVGMat.149']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_120.geometry}
          material={materials['SVGMat.148']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_121.geometry}
          material={materials['SVGMat.147']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_122.geometry}
          material={materials['SVGMat.146']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_123.geometry}
          material={materials['SVGMat.145']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_124.geometry}
          material={materials['SVGMat.143']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_125.geometry}
          material={materials['SVGMat.142']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_126.geometry}
          material={materials['SVGMat.141']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_127.geometry}
          material={materials['SVGMat.140']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_128.geometry}
          material={materials['SVGMat.139']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_129.geometry}
          material={materials['SVGMat.138']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_130.geometry}
          material={materials['SVGMat.137']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_131.geometry}
          material={materials['SVGMat.136']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_132.geometry}
          material={materials['SVGMat.135']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_133.geometry}
          material={materials['SVGMat.134']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_134.geometry}
          material={materials['SVGMat.133']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_135.geometry}
          material={materials['SVGMat.132']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_136.geometry}
          material={materials['SVGMat.131']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_137.geometry}
          material={materials['SVGMat.130']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_138.geometry}
          material={materials['SVGMat.129']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_139.geometry}
          material={materials['SVGMat.128']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_140.geometry}
          material={materials['SVGMat.127']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_141.geometry}
          material={materials['SVGMat.126']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_142.geometry}
          material={materials['SVGMat.125']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_143.geometry}
          material={materials['SVGMat.124']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_144.geometry}
          material={materials['SVGMat.123']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_145.geometry}
          material={materials['SVGMat.122']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_146.geometry}
          material={materials['SVGMat.121']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_147.geometry}
          material={materials['SVGMat.120']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_148.geometry}
          material={materials['SVGMat.119']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_149.geometry}
          material={materials['SVGMat.118']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_150.geometry}
          material={materials['SVGMat.117']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_151.geometry}
          material={materials['SVGMat.116']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_152.geometry}
          material={materials['SVGMat.115']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_153.geometry}
          material={materials['SVGMat.114']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_154.geometry}
          material={materials['SVGMat.113']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_155.geometry}
          material={materials['SVGMat.112']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_156.geometry}
          material={materials['SVGMat.111']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_157.geometry}
          material={materials['SVGMat.110']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_158.geometry}
          material={materials['SVGMat.109']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_159.geometry}
          material={materials['SVGMat.108']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_160.geometry}
          material={materials['SVGMat.107']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_161.geometry}
          material={materials['SVGMat.106']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_162.geometry}
          material={materials['SVGMat.105']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_163.geometry}
          material={materials['SVGMat.104']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_164.geometry}
          material={materials['SVGMat.103']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_165.geometry}
          material={materials['SVGMat.102']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_166.geometry}
          material={materials['SVGMat.101']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_167.geometry}
          material={materials['SVGMat.100']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_168.geometry}
          material={materials['SVGMat.099']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_169.geometry}
          material={materials['SVGMat.098']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_170.geometry}
          material={materials['SVGMat.097']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_171.geometry}
          material={materials['SVGMat.096']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_172.geometry}
          material={materials['SVGMat.095']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_173.geometry}
          material={materials['SVGMat.094']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_174.geometry}
          material={materials['SVGMat.093']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_175.geometry}
          material={materials['SVGMat.092']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_176.geometry}
          material={materials['SVGMat.091']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_177.geometry}
          material={materials['SVGMat.090']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_178.geometry}
          material={materials['SVGMat.089']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_179.geometry}
          material={materials['SVGMat.088']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_180.geometry}
          material={materials['SVGMat.087']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_181.geometry}
          material={materials['SVGMat.086']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_182.geometry}
          material={materials['SVGMat.085']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_183.geometry}
          material={materials['SVGMat.084']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_184.geometry}
          material={materials['SVGMat.083']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_185.geometry}
          material={materials['SVGMat.082']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_186.geometry}
          material={materials['SVGMat.081']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_187.geometry}
          material={materials['SVGMat.080']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_188.geometry}
          material={materials['SVGMat.079']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_189.geometry}
          material={materials['SVGMat.078']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_190.geometry}
          material={materials['SVGMat.077']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_191.geometry}
          material={materials['SVGMat.076']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_192.geometry}
          material={materials['SVGMat.075']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_193.geometry}
          material={materials['SVGMat.074']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_194.geometry}
          material={materials['SVGMat.073']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_195.geometry}
          material={materials['SVGMat.072']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_196.geometry}
          material={materials['SVGMat.071']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_197.geometry}
          material={materials['SVGMat.070']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_198.geometry}
          material={materials['SVGMat.069']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_199.geometry}
          material={materials['SVGMat.068']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_200.geometry}
          material={materials['SVGMat.066']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_201.geometry}
          material={materials['SVGMat.065']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_202.geometry}
          material={materials['SVGMat.064']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_203.geometry}
          material={materials['SVGMat.063']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_204.geometry}
          material={materials['SVGMat.062']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_205.geometry}
          material={materials['SVGMat.061']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_206.geometry}
          material={materials['SVGMat.060']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_207.geometry}
          material={materials['SVGMat.059']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_208.geometry}
          material={materials['SVGMat.058']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_209.geometry}
          material={materials['SVGMat.055']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_210.geometry}
          material={materials['SVGMat.054']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_211.geometry}
          material={materials['SVGMat.053']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_212.geometry}
          material={materials['SVGMat.052']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_213.geometry}
          material={materials['SVGMat.051']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_214.geometry}
          material={materials['SVGMat.050']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_215.geometry}
          material={materials['SVGMat.049']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_216.geometry}
          material={materials['SVGMat.048']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_217.geometry}
          material={materials['SVGMat.047']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_218.geometry}
          material={materials['SVGMat.046']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_219.geometry}
          material={materials['SVGMat.045']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_220.geometry}
          material={materials['SVGMat.044']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_221.geometry}
          material={materials['SVGMat.043']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_222.geometry}
          material={materials['SVGMat.042']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_223.geometry}
          material={materials['SVGMat.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_224.geometry}
          material={materials['SVGMat.040']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_225.geometry}
          material={materials['SVGMat.039']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_226.geometry}
          material={materials['SVGMat.038']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_227.geometry}
          material={materials['SVGMat.037']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_228.geometry}
          material={materials['SVGMat.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_229.geometry}
          material={materials['SVGMat.035']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_230.geometry}
          material={materials['SVGMat.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_231.geometry}
          material={materials['SVGMat.033']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_232.geometry}
          material={materials['SVGMat.032']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_233.geometry}
          material={materials['SVGMat.031']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_234.geometry}
          material={materials['SVGMat.030']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_235.geometry}
          material={materials['SVGMat.029']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_236.geometry}
          material={materials['SVGMat.028']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_237.geometry}
          material={materials['SVGMat.027']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_238.geometry}
          material={materials['SVGMat.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_239.geometry}
          material={materials['SVGMat.025']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_240.geometry}
          material={materials['SVGMat.024']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_241.geometry}
          material={materials['SVGMat.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_242.geometry}
          material={materials['SVGMat.022']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_243.geometry}
          material={materials['SVGMat.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_244.geometry}
          material={materials['SVGMat.020']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_245.geometry}
          material={materials['SVGMat.018']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_246.geometry}
          material={materials['SVGMat.017']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_247.geometry}
          material={materials['SVGMat.014']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_248.geometry}
          material={materials['SVGMat.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_249.geometry}
          material={materials['SVGMat.015']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_250.geometry}
          material={materials['SVGMat.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_251.geometry}
          material={materials['SVGMat.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve025_252.geometry}
          material={materials['SVGMat.002']}
        />
      </group>
    </group>
  )
}
